--
-- PostgreSQL database dump
--

-- Dumped from database version 14.10
-- Dumped by pg_dump version 14.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: get_list_map; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.get_list_map (
    id integer NOT NULL,
    status character varying(255),
    task character varying(255)
);


ALTER TABLE public.get_list_map OWNER TO postgres;

--
-- Name: todo_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.todo_list (
    id integer NOT NULL,
    status character varying(255),
    task character varying(255)
);


ALTER TABLE public.todo_list OWNER TO postgres;

--
-- Name: todo_list_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.todo_list ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.todo_list_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: get_list_map; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.get_list_map (id, status, task) FROM stdin;
\.


--
-- Data for Name: todo_list; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.todo_list (id, status, task) FROM stdin;
1	ToDo	testing
\.


--
-- Name: todo_list_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.todo_list_id_seq', 2, true);


--
-- Name: get_list_map get_list_map_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.get_list_map
    ADD CONSTRAINT get_list_map_pkey PRIMARY KEY (id);


--
-- Name: todo_list todo_list_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.todo_list
    ADD CONSTRAINT todo_list_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

